run:
  concurrency: 4
  deadline: 1m
  issues-exit-code: 1
  tests: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable:
    - godox
    - gochecknoglobals
    - gochecknoinits
    - lll
    - misspell
    - depguard
    - maligned
    - stylecheck
    - gofmt
  enable:
    - govet
    - goimports
    - gocritic
    - gosimple
    - gocyclo
    - goconst
    - gosec
    - errcheck
    - staticcheck
    - golint
    - structcheck
    - typecheck
    - varcheck
    - unused
    - ineffassign
    - deadcode
    - unconvert
    - interfacer
    - funlen
    - bodyclose
    - whitespace
    - scopelint
    - prealloc
    - nakedret
    - dogsled
    - unparam
  fast: false

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    # a path to a file containing a list of functions to be excluded.

  funlen:
    lines: 60
    statements: 40

  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 2

  govet:
    check-shadowing: false
    # enable or disable analyzers by name
    enable:
      - atomicalign
    enable-all: false
    disable:
      - shadow
    disable-all: false

  goimports:
    local-prefixes: waitabit,github.com/heartwilltell

  gocyclo:
    min-complexity: 10

  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 100

  goconst:
    # minimal length of string constant, 3 by default
    min-len: 3
    # minimal occurrences count to trigger, 3 by default
    min-occurrences: 3

  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/sirupsen/logrus
    packages-with-error-messages:
      # specify an error message to output when a blacklisted package is used
      github.com/sirupsen/logrus: "logging is allowed only by logutils.Log"
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
    ignore-words:
      - someword
  lll:
    line-length: 200
    tab-width: 1

  unused:
    check-exported: false

  unparam:
    # Inspect exported functions, default is false. Set to true if no external program/library imports your code.
    # XXX: if you enable this setting, unparam will report a lot of false-positives in text editors:
    # if it's called for subdir of a project it can't find external interfaces. All text editor integrations
    # with golangci-lint call it on a directory with the changed file.
    check-exported: false

  nakedret:
    # make an issue if func has more lines of code than this setting and it has naked returns; default is 30
    max-func-lines: 30

  prealloc:
    # XXX: we don't recommend using this linter before doing performance profiling.
    # For most programs usage of prealloc will be a premature optimization.

    # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them.
    # True by default.
    simple: true
    range-loops: true # Report preallocation suggestions on range loops, true by default
    for-loops: false # Report preallocation suggestions on for loops, false by default

  gocritic:
    # Which checks should be enabled; can't be combined with 'disabled-checks';
    # See https://go-critic.github.io/overview#checks-overview
    # To check which checks are enabled run `GL_DEBUG=gocritic golangci-lint run`
    # By default list of stable checks is used.
    enabled-checks:

    # Which checks should be disabled; can't be combined with 'enabled-checks'; default is empty
    disabled-checks:
      - regexpMust

    settings: # settings passed to gocritic
      captLocal: # must be valid enabled check name
        paramsOnly: true

  godox:
    # report any comments starting with keywords, this is useful for TODO or FIXME comments that
    # might be left in the code accidentally and should be resolved before merging
    keywords: # default keywords are TODO, BUG, and FIXME, these can be overwritten by this setting
      - NOTE
      - OPTIMIZE # marks code that should be optimized before merging
      - HACK # marks hack-arounds that should be removed before merging

  dogsled:
    max-blank-identifiers: 2

  whitespace:
    multi-if: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

    - path: internal/hmac/
      text: "weak cryptographic primitive"
      linters:
        - gosec

    - linters:
        - gosec
      text: "G104:"

    - linters:
        - staticcheck
      text: "SA9003:"

    - linters:
        - lll
      source: "^//go:generate "

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false