name: Lint Test Build
on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Lint
        uses: heartwilltell/action-golangci-lint@master
          
